### PR TITLE
Add GitHub resources and tutorials

### PR DESCRIPTION
**Pull request by RyanFitzgerald**
#5

Added additional resources and tutorials on how to use GitHub, create and understand issues, and setup new projects.

### CODE REVIEW

**Comment by betatim** [comment]
Looks good to me.

Should we keep #5 open after merging this to attract more resources?

**Comment by betatim** [comment]
Could you rebase this branch so that we can merge it? Let me know if you'd like some help with the git-fu to make a rebase happen.

**Comment by RyanFitzgerald** [comment]
Sorry for the delayed response! It should be good to go now.

Please let me know if you need anything else.

**Comment by betatim** [comment]
Superstar!

**Pull request merged**
