### PR TITLE
Remove max-width:1400px; Update Mozilla logo; Add black color at footer

### PR DESCRIPTION
**Pull request by barrosgg**

### CODE REVIEW

**Comment by barrosgg** [comment]
Hi Abby,

I've some suggestions here:

1. Remove max-width:1400px to [improve the responsiveness](https://screenshots.firefox.com/ksWgX10w4xVILS54/127.0.0.1).
2. Update the Mozilla logo
3. Add black color at footer, that's more common at all Mozilla pages.

Live at: https://barrosgeraldo.github.io/open-leadership-training-series/

**Review by abbycabs — CHANGES_REQUESTED** [review]
Thank you so much for this @barrosgeraldo! Sorry for my slow response here

The logo is great and the black footer is perfect. Removing the max-width affects the readability at larger screens -- is there a way to fix the responsiveness while restricting the text width in the column? Let me know if that makes sense!

**Comment by barrosgg** [comment]
Hi @acabunoc, when I removed this I did some testing and it worked fine, no problem with responsiveness.
Check it here: https://barrosgeraldo.github.io/open-leadership-training-series/

**Comment by abbycabs** [comment]
@barrosgeraldo the line lengths get really long:
screen shot 2017-11-21 at 2 19 54 pm

**Comment by barrosgg** [comment]
Humm, yeah, I got it, let's keep the max-width:1400px then, and I'll try to solve this and send another one in the next few weeks.

**Review by abbycabs — APPROVED** [review]

**Comment by abbycabs** [comment]
Thanks @barrosgeraldo!

**Pull request merged**
