### PR TITLE
add local install instructions

### LINKED ISSUE #14: No instructions for local previewing
Should add a simple recipe to `CONTRIBUTING.md` or so that explains how to render things locally so you can see what you did before it goes live.

I have a feeling there is one node package that does it all, but can never remember.

### PR DESCRIPTION
**Pull request by abbycabs**
- this should fix #14

### CODE REVIEW

**Comment by abbycabs** [comment]
Hey @betatim, do these instructions work for you?

**Comment by betatim** [comment]
Kind of :-/

```
$ bundle install
....
Installing sawyer 0.7.0
An error occurred while installing nokogiri (1.6.8.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8.1'` succeeds before bundling.

$ gem install nokogiri -v '1.6.8.1'
```

nokogiri fails with compiler errors. I'll have to investigate if that is something weird on my machine because I don't ever use ruby or what.

**Comment by betatim** [comment]
After upgrading XCode (and reinstalling the dev tools) the error changed to something about `lzma`. That error is discussed here: sparklemotion/nokogiri#1483 and the solution is to `brew install xv --universal` after that `bundle install` succeeds.

Big 👍  from me.

**Comment by abbycabs** [comment]
@betatim should we modify the instructions to prevent your error?

**Comment by abbycabs** [comment]
Gonna merge in for now! Let's make a new issue if we want more comprehensive install instructions 😄 Thanks for going through all that @betatim! upgrading XCode is not easy...

**Comment by betatim** [comment]
Not sure it is possible to make comprehensive instructions. It should just work but if it doesn't it is probably weird obscure errors that are all wonderfully unique snowflakes :-/ So I'd keep it as it is

**Pull request merged**
