### PR TITLE
adding google analytics

### PR DESCRIPTION
**Pull request by abbycabs**
just got a property (thanks @cadecairos)

not sure if we'll need add an additional do not track script somewhere

### CODE REVIEW

**Comment by betatim** [comment]
Are there any requirements/being a good citizen regarding telling visitors that they are being tracked with GA? Not something I have a lot of experience with TBH.

Did a bit of googling and found: https://til.hashrocket.com/posts/8e5a5f0266-respect-do-not-track

**Comment by cadecairos** [comment]
If we want to link to it, Mozilla's usage of Google Analytics is described in this article: https://www.mozilla.org/en-US/privacy/websites/ 

I also linked the DNT respecting GA injection code to @acabunoc on Friday,  so let's be sure to use that. 

Edit:  this is the snippet that respects DNT,  and works in multiple browsers: https://gist.github.com/cadecairos/416e7abe6aab11b8317833924ed1e45d

**Comment by abbycabs** [comment]
I need to update this to use DNT! Thank @cadecairos + @betatim

**Comment by abbycabs** [comment]
I updated the PR to respect DNT. I also made an issue to think about linking to the article describing  Mozilla's usage of Google Analytics #69

**Comment by betatim** [comment]
Merge time?

**Comment by betatim** [comment]
Bazinga! :rocket:

**Pull request merged**
